### ISSUE TITLE
Integration of CircleCI with AWS ECR

### ISSUE THREAD

**Issue by akamalov** [circleci/circle-ecs#2]
Hello Kevin,

Thanks for a nice write-up. Small question: If I am using your repo (circle-ecs), but I want to do pull off Amazon ECR instead of Docker HUB, how would one proceed ? Right now in CircleCI I am getting stuck at 

```
"docker pull XXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/akamalov/nginx-base | cat
Using default tag: latest
Pulling repository XXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/akamalov/nginx-base

Please login prior to pull:
```

How would one pass on credentials? I know that Codeship addresses this issue by requiring to encrypt the credentials with a key (they pass AES key to you which you use then to encrypt your credentials which gets then decrypted and used by Codeship.

Thanks!!!

Alex

**Comment by itajaja** [comment]
Hi! Here is a script I am currently using:

``` sh
#!/bin/sh
set -ev

$image_name="XXXXXXX"

docker_login=`aws ecr get-login`
ECR_REGISTRY=`echo $docker_login | sed 's|.*https://||'`

eval "$docker_login"

docker tag -f bacta:latest $ECR_REGISTRY/$image_name:latest
docker push $ECR_REGISTRY/$image_name:latest
```

**Comment by akamalov** [comment]
Thanks Giacomo!!

**Comment by bellkev** [comment]
Sorry for the slow reply, but glad you were able to figure this out! FYI, we plan to have more in-depth docs/examples of ECS/ECR out soon :)
