### ISSUE TITLE
build.sh creates the task but service is still running the old one

### ISSUE THREAD

**Issue by billbuilder** [circleci/circle-ecs#3]
When I run the build.sh, a new revision from the task is created, but the cluster still keeps running the old revision on Amazon ECS.

The file ran successfully:

```
33f482......b86d64: digest: sha256:ae31.......ec8 size: 31290
Revision: arn:aws:ecs:us-east-1......:11
Waiting for stale deployments:
arn:aws:ecs:us-east-1:......:10
Deployed!
```

Revision 11 is present, but revision 10 is still running. I have to stop manually the running task and start a new one using revision 11.

Any idea? Thank you in advance!

**Comment by bellkev** [comment]
I believe the service update should automatically kill the old tasks: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/update-service.html This can take a little while though. Are you sure the old tasks never go away?

**Comment by billbuilder** [comment]
I'm pretty sure. :)

**Comment by billbuilder** [comment]
The service is allowed to have multiple tasks, still Amazon returns well following your script.
I strongly believe to find this bug on Amazon's side, was just wondering if anyone else had to deal with it and a workaround popped up somewhere ...

**Comment by bellkev** [comment]
Yeah, the service can definitely have many task instances of different versions, but I _think_ it only has one task definition set at any given time and that it rolls over old task instances to try to get everything on the latest version. I'm not 100% sure on this though. The AWS docs are obviously the source of truth here, and I'd check with AWS support if you still see something unexpected.

Closing for now, but please reopen if you see more details about something wrong with the script.

**Comment by PLaRoche** [comment]
@bellkev I'm having this issue, seems to be around pushing up a task def that has the same port number as the previous in a one Ec2 instance cluster
