### ISSUE TITLE
Deploy.sh is too cryptic

### ISSUE THREAD

**Issue by zacharyclaysmith** [circleci/circle-ecs#4]
There are a lot of "magic values" floating around the deploy.sh file, which makes it extremely difficult to modify with confidence. A few comments explaining the values that need to be (or can optionally be) modified would save future developers a significant amount of time.

**Comment by bellkev** [comment]
Do you mind specifying which values in particular? They should mostly at least be listed in the readme or they are standard CircleCI env vars as documented here: https://circleci.com/docs/environment

I'll admit the use of global variables like $task_def and $revision is a bit sloppy, but bash makes it pretty hard not to use global variables. I could have picked another approach like echoing to stdout from functions and using command substitution, but that's also kind of a pain.

**Comment by zacharyclaysmith** [comment]
For posterity, here's the script I ended up with after a few days of hacking to integrate with ECS (I'm not a bash scripter). Will close this issue. (I redacted my personal data, so apologies if there are any late typos)

https://gist.github.com/zacharyclaysmith/6691bcd8ed2fb73db77a
